package com.lumi.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ArticleTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleTagAllPropertiesEquals(ArticleTag expected, ArticleTag actual) {
        assertArticleTagAutoGeneratedPropertiesEquals(expected, actual);
        assertArticleTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleTagAllUpdatablePropertiesEquals(ArticleTag expected, ArticleTag actual) {
        assertArticleTagUpdatableFieldsEquals(expected, actual);
        assertArticleTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleTagAutoGeneratedPropertiesEquals(ArticleTag expected, ArticleTag actual) {
        assertThat(actual)
            .as("Verify ArticleTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleTagUpdatableFieldsEquals(ArticleTag expected, ArticleTag actual) {
        assertThat(actual)
            .as("Verify ArticleTag relevant properties")
            .satisfies(a -> assertThat(a.getArticleId()).as("check articleId").isEqualTo(expected.getArticleId()))
            .satisfies(a -> assertThat(a.getTagId()).as("check tagId").isEqualTo(expected.getTagId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertArticleTagUpdatableRelationshipsEquals(ArticleTag expected, ArticleTag actual) {
        // empty method
    }
}
