package com.lumi.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class KnowledgeCategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeCategoryAllPropertiesEquals(KnowledgeCategory expected, KnowledgeCategory actual) {
        assertKnowledgeCategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertKnowledgeCategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeCategoryAllUpdatablePropertiesEquals(KnowledgeCategory expected, KnowledgeCategory actual) {
        assertKnowledgeCategoryUpdatableFieldsEquals(expected, actual);
        assertKnowledgeCategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeCategoryAutoGeneratedPropertiesEquals(KnowledgeCategory expected, KnowledgeCategory actual) {
        assertThat(actual)
            .as("Verify KnowledgeCategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeCategoryUpdatableFieldsEquals(KnowledgeCategory expected, KnowledgeCategory actual) {
        assertThat(actual)
            .as("Verify KnowledgeCategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getSlug()).as("check slug").isEqualTo(expected.getSlug()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertKnowledgeCategoryUpdatableRelationshipsEquals(KnowledgeCategory expected, KnowledgeCategory actual) {
        // empty method
    }
}
