export enum TicketStatus {
  OPEN = 'OPEN',

  IN_PROGRESS = 'IN_PROGRESS',

  WAITING_CUSTOMER = 'WAITING_CUSTOMER',

  WAITING_THIRD_PARTY = 'WAITING_THIRD_PARTY',

  RESOLVED = 'RESOLVED',

  CLOSED = 'CLOSED',
}
