package com.lumi.app.domain;

import static com.lumi.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ClothSupplementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothSupplementAllPropertiesEquals(ClothSupplement expected, ClothSupplement actual) {
        assertClothSupplementAutoGeneratedPropertiesEquals(expected, actual);
        assertClothSupplementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothSupplementAllUpdatablePropertiesEquals(ClothSupplement expected, ClothSupplement actual) {
        assertClothSupplementUpdatableFieldsEquals(expected, actual);
        assertClothSupplementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothSupplementAutoGeneratedPropertiesEquals(ClothSupplement expected, ClothSupplement actual) {
        assertThat(actual)
            .as("Verify ClothSupplement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothSupplementUpdatableFieldsEquals(ClothSupplement expected, ClothSupplement actual) {
        assertThat(actual)
            .as("Verify ClothSupplement relevant properties")
            .satisfies(a -> assertThat(a.getClothId()).as("check clothId").isEqualTo(expected.getClothId()))
            .satisfies(a -> assertThat(a.getSupplierId()).as("check supplierId").isEqualTo(expected.getSupplierId()))
            .satisfies(a ->
                assertThat(a.getSupplyPrice())
                    .as("check supplyPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSupplyPrice())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getLeadTimeDays()).as("check leadTimeDays").isEqualTo(expected.getLeadTimeDays()))
            .satisfies(a -> assertThat(a.getMinOrderQty()).as("check minOrderQty").isEqualTo(expected.getMinOrderQty()))
            .satisfies(a -> assertThat(a.getIsPreferred()).as("check isPreferred").isEqualTo(expected.getIsPreferred()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothSupplementUpdatableRelationshipsEquals(ClothSupplement expected, ClothSupplement actual) {
        // empty method
    }
}
