package com.lumi.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ClothProductMapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothProductMapAllPropertiesEquals(ClothProductMap expected, ClothProductMap actual) {
        assertClothProductMapAutoGeneratedPropertiesEquals(expected, actual);
        assertClothProductMapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothProductMapAllUpdatablePropertiesEquals(ClothProductMap expected, ClothProductMap actual) {
        assertClothProductMapUpdatableFieldsEquals(expected, actual);
        assertClothProductMapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothProductMapAutoGeneratedPropertiesEquals(ClothProductMap expected, ClothProductMap actual) {
        assertThat(actual)
            .as("Verify ClothProductMap auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothProductMapUpdatableFieldsEquals(ClothProductMap expected, ClothProductMap actual) {
        assertThat(actual)
            .as("Verify ClothProductMap relevant properties")
            .satisfies(a -> assertThat(a.getClothId()).as("check clothId").isEqualTo(expected.getClothId()))
            .satisfies(a -> assertThat(a.getProductId()).as("check productId").isEqualTo(expected.getProductId()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getUnit()).as("check unit").isEqualTo(expected.getUnit()))
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertClothProductMapUpdatableRelationshipsEquals(ClothProductMap expected, ClothProductMap actual) {
        // empty method
    }
}
