package com.lumi.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TicketTagAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTagAllPropertiesEquals(TicketTag expected, TicketTag actual) {
        assertTicketTagAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketTagAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTagAllUpdatablePropertiesEquals(TicketTag expected, TicketTag actual) {
        assertTicketTagUpdatableFieldsEquals(expected, actual);
        assertTicketTagUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTagAutoGeneratedPropertiesEquals(TicketTag expected, TicketTag actual) {
        assertThat(actual)
            .as("Verify TicketTag auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTagUpdatableFieldsEquals(TicketTag expected, TicketTag actual) {
        assertThat(actual)
            .as("Verify TicketTag relevant properties")
            .satisfies(a -> assertThat(a.getTicketId()).as("check ticketId").isEqualTo(expected.getTicketId()))
            .satisfies(a -> assertThat(a.getTagId()).as("check tagId").isEqualTo(expected.getTagId()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTagUpdatableRelationshipsEquals(TicketTag expected, TicketTag actual) {
        // empty method
    }
}
